-- CreateTable
CREATE TABLE `SubOrder` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `orderId` INTEGER NOT NULL,
    `orderNumber` VARCHAR(191) NULL,
    `quotationNumber` VARCHAR(191) NULL,
    `customerName` VARCHAR(191) NULL,
    `productCode` VARCHAR(191) NULL,
    `jobname` VARCHAR(191) NULL,
    `salesManager` VARCHAR(191) NULL,
    `contact` VARCHAR(191) NULL,
    `c` VARCHAR(191) NULL,
    `telephoneNumber` VARCHAR(191) NULL,
    `email` VARCHAR(191) NULL,
    `typeOfPrinterMachine` ENUM('LETTERPRESS', 'F31F32', 'D2', 'S29', 'OUTSOURCE') NULL,
    `cmyk` BOOLEAN NULL,
    `cmykBlack` BOOLEAN NULL,
    `cmykEtc` BOOLEAN NULL,
    `pantone` BOOLEAN NULL,
    `subPantone` VARCHAR(191) NULL,
    `original` BOOLEAN NULL,
    `digitalProof` BOOLEAN NULL,
    `originalErp` BOOLEAN NULL,
    `subErp` VARCHAR(191) NULL,
    `blankTest` BOOLEAN NULL,
    `blank` BOOLEAN NULL,
    `spotUv` BOOLEAN NULL,
    `removeGlue` BOOLEAN NULL,
    `leaveCoatingUv` BOOLEAN NULL,
    `pumpHoleEyeAndVine` BOOLEAN NULL,
    `originalEtc` BOOLEAN NULL,
    `subOriginalErp` VARCHAR(191) NULL,
    `sticker` BOOLEAN NULL,
    `offset` BOOLEAN NULL,
    `fsc` BOOLEAN NULL,
    `coated` ENUM('POG', 'POM', 'BOPP') NULL,
    `coatedEtc` VARCHAR(191) NULL,
    `uv` ENUM('GLOSS', 'MATT') NULL,
    `coldFoil` ENUM('SILVER', 'GOLD') NULL,
    `coldFoilEtc` VARCHAR(191) NULL,
    `materialSticker` VARCHAR(191) NULL,
    `materialFSC` BOOLEAN NULL,
    `unitSizeFrontY` VARCHAR(191) NULL,
    `unitSizeFrontX` VARCHAR(191) NULL,
    `unitSizeBlackY` VARCHAR(191) NULL,
    `unitSizeBlackX` VARCHAR(191) NULL,
    `typeOfCorner` ENUM('UPPERCORNER', 'SQUARES', 'ASJOBLAYOUT') NULL,
    `subUpperCorner` VARCHAR(191) NULL,
    `typeOfPacking` ENUM('SHEET', 'ROLL') NULL,
    `subSheet` VARCHAR(191) NULL,
    `subRoll` VARCHAR(191) NULL,
    `space` VARCHAR(191) NULL,
    `core` ENUM('ONEINCH', 'ONEPONITFIVEINCH', 'THREEINCH') NULL,
    `purchaseOrderQty` INTEGER NULL,
    `roll` ENUM('OUTERROLL', 'INSIDEROLL') NULL,
    `subOuterRoll` ENUM('OUTERROLLFRONTHEADSIDE', 'OUTERROLLFRONTBACKSIDE', 'OUTERROLLFRONTRIGHTSIDE', 'OUTERROLLFRONTLEFTSIDE', 'OUTERROLLBACKHEADSIDE', 'OUTERROLLBACKBACKSIDE', 'OUTERROLLBACKRIGHTSIDE', 'OUTERROLLBACKLEFTSIDE', 'OUTERROLLFRONTBACKRIGHTSIDE', 'OUTERROLLFRONTBACKLEFTSIDE') NULL,
    `insideRollRemark` VARCHAR(191) NULL,
    `remark` VARCHAR(500) NULL,
    `erp` VARCHAR(191) NULL,
    `confirm` VARCHAR(191) NULL,
    `rev` VARCHAR(191) NULL,
    `salesCoName` VARCHAR(191) NULL,
    `salesCoDate` VARCHAR(191) NULL,
    `salesCoTime` VARCHAR(191) NULL,
    `salesCoMgr` VARCHAR(191) NULL,
    `salesCoMgrDate` VARCHAR(191) NULL,
    `salesCoMgrTime` VARCHAR(191) NULL,
    `prepressName` VARCHAR(191) NULL,
    `prepressDate` VARCHAR(191) NULL,
    `prepressTime` VARCHAR(191) NULL,
    `prepressNameCheckedBy` VARCHAR(191) NULL,
    `prepressDateCheckedBy` VARCHAR(191) NULL,
    `prepressTimeCheckedBy` VARCHAR(191) NULL,
    `prepressRemark` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `SubOrder` ADD CONSTRAINT `SubOrder_orderId_fkey` FOREIGN KEY (`orderId`) REFERENCES `Order`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
